---
- hosts: worker
  become: yes
  tasks:

    - name: Set up Node.js repository
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs-16.16.0

    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Set up MongoDB repository
      yum_repository:
        name: mongodb-org-6.0
        description: MongoDB Repository
        baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/6.0/x86_64/
        gpgcheck: yes
        enabled: yes
        gpgkey: https://www.mongodb.org/static/pgp/server-6.0.asc

    - name: Install MongoDB
      yum:
        name: mongodb-org
        state: present

    - name: Start MongoDB service
      systemd:
        state: started
        name: mongod

    - name: Install frontend dependencies
      npm:
        path: /home/ec2-user/final-project/medcare

    - name: Build frontend
      command: npm run build
      args:
        chdir: /home/ec2-user/final-project/medcare

    - name: Start frontend
      command: npm start
      args:
        chdir: /home/ec2-user/final-project/medcare

    - name: Install backend dependencies
      npm:
        path: /home/ec2-user/final-project/medcare-server

    - name: Start backend
      command: npm start
      args:
        chdir: /home/ec2-user/final-project/medcare-server
      environment:
        MONGODB_URI: mongodb://65.2.143.142:27017/Medcare
